# backend/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Copier les fichiers package
COPY package*.json ./
COPY package-lock*.json ./

# Installer les dépendances
RUN npm install --legacy-peer-deps

# Copier le code source
COPY . .

# Créer le dossier uploads
RUN mkdir -p /app/uploads/profiles /app/uploads/temp

EXPOSE 3000

CMD ["npm", "run", "start:dev"]