# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install && npm cache clean --force

# Copier le reste du code
COPY . .

# Installer nodemon pour le hot-reload
RUN npm install -g nodemon

# Créer les dossiers uploads
RUN mkdir -p /app/uploads/profiles /app/uploads/temp

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]